/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package first;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sukanta
 */
public class AdminLoginGUI1 extends javax.swing.JFrame {

    /**
     * Creates new form AdminLoginGUI1
     */
    public AdminLoginGUI1() {
        initComponents();
        //setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lSignIn = new javax.swing.JLabel();
        lAdminID = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        tAdminID = new javax.swing.JTextField();
        adminImage = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();
        bSignIn = new javax.swing.JButton();
        bBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign in as Administrator");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setMaximumSize(new java.awt.Dimension(677, 426));
        setMinimumSize(new java.awt.Dimension(677, 440));
        setResizable(false);
        getContentPane().setLayout(null);

        lSignIn.setFont(new java.awt.Font("Narkisim", 1, 36)); // NOI18N
        lSignIn.setForeground(new java.awt.Color(0, 0, 255));
        lSignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lSignIn.setText("SIGN IN");
        getContentPane().add(lSignIn);
        lSignIn.setBounds(10, 20, 153, 60);

        lAdminID.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lAdminID.setForeground(new java.awt.Color(63, 126, 76));
        lAdminID.setText("Admin ID");
        getContentPane().add(lAdminID);
        lAdminID.setBounds(10, 147, 153, 44);

        lPassword.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lPassword.setForeground(new java.awt.Color(151, 86, 154));
        lPassword.setText("Password");
        getContentPane().add(lPassword);
        lPassword.setBounds(10, 228, 153, 46);

        tAdminID.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(tAdminID);
        tAdminID.setBounds(181, 152, 255, 44);

        adminImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sukanta\\Pictures\\admin.jpg")); // NOI18N
        adminImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(adminImage);
        adminImage.setBounds(446, 74, 204, 204);

        tPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(tPassword);
        tPassword.setBounds(183, 228, 253, 43);

        bSignIn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sukanta\\Pictures\\login button.jpg")); // NOI18N
        bSignIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignInActionPerformed(evt);
            }
        });
        getContentPane().add(bSignIn);
        bSignIn.setBounds(361, 319, 246, 66);

        bBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sukanta\\Pictures\\back button.png")); // NOI18N
        bBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });
        getContentPane().add(bBack);
        bBack.setBounds(45, 319, 189, 66);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sukanta\\Pictures\\(8).jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        int rply=JOptionPane.showConfirmDialog(this, "Do you want to go in previous page?");
			if(rply == JOptionPane.YES_OPTION)
			{
				JFrame HomePageGUI = new HomePageGUI();
                                HomePageGUI.setVisible(true);
                                setVisible(false);
			}
    }//GEN-LAST:event_bBackActionPerformed

    private void bSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignInActionPerformed
        String sID = tAdminID.getText().trim();
	String sPasword = tPassword.getText().trim();
	if(sID.equals("admin") && sPasword.equals("admin"))
	{
		/*String loginDate, loginTime;
		loginDate = lDateValue.getText();
		loginTime = lTimeValue.getText();
		JOptionPane.showMessageDialog(this, "Login Date " + loginDate);
		JOptionPane.showMessageDialog(this, "Login time " + loginTime);*/
		JOptionPane.showMessageDialog(this, "You are succesfully logged in");
		
                JFrame AdminPageGUI1 = new AdminPageGUI1();
                AdminPageGUI1.setVisible(true);
		setVisible(false);
	}
	else
	{
            JOptionPane.showMessageDialog(this, "Worng entry.\nTry Again.");
            tAdminID.setText("");
            tPassword.setText("");
				
	}
    }//GEN-LAST:event_bSignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLoginGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLoginGUI1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminImage;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lAdminID;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lSignIn;
    private javax.swing.JTextField tAdminID;
    private javax.swing.JPasswordField tPassword;
    // End of variables declaration//GEN-END:variables
}
