/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package first;

import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sukanta
 */
public class AdminPageGUI1 extends javax.swing.JFrame {
    private String sysDate,sysTime;

    /**
     * Creates new form AdminPageGUI1
     */
    public AdminPageGUI1() {
        initComponents();
        setResizable(false);
        
        
        /****** System date and time**************/
        Calendar cal = Calendar.getInstance();
		
		String cday = ""+cal.get(Calendar.DATE);
		int x =cal.get(Calendar.MONTH);
		String cmonth = ""+(x+1);
		String cyear =""+cal.get(Calendar.YEAR);
		sysDate = cday+"/"+cmonth+"/"+cyear;
		
		//lDateValue=new JLabel(sysDate);	
                this.lDateValue.setText(sysDate);
		
		
		String chr = ""+cal.get(Calendar.HOUR_OF_DAY);
		String cmin = ""+cal.get(Calendar.MINUTE);
		String csec =""+cal.get(Calendar.SECOND);
		sysTime = chr+":"+cmin+":"+csec;
		
		//lTimeValue=new JLabel(sysTime);
                this.lTimeValue.setText(sysTime);
                /*********************************************/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lDate = new javax.swing.JLabel();
        lTime = new javax.swing.JLabel();
        lDateValue = new javax.swing.JLabel();
        lTimeValue = new javax.swing.JLabel();
        bAddOperator = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setMaximumSize(new java.awt.Dimension(843, 472));
        setMinimumSize(new java.awt.Dimension(843, 482));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 47, 224));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO ADMINISTRATOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 11, 497, 55);

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sukanta\\Pictures\\admin.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2);
        jLabel2.setBounds(625, 95, 208, 206);

        lDate.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        lDate.setForeground(new java.awt.Color(204, 0, 0));
        lDate.setText("Current Date");
        getContentPane().add(lDate);
        lDate.setBounds(10, 79, 172, 32);

        lTime.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        lTime.setForeground(new java.awt.Color(204, 0, 51));
        lTime.setText("Current Time");
        getContentPane().add(lTime);
        lTime.setBounds(10, 117, 172, 32);

        lDateValue.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        getContentPane().add(lDateValue);
        lDateValue.setBounds(200, 79, 202, 35);

        lTimeValue.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        getContentPane().add(lTimeValue);
        lTimeValue.setBounds(200, 117, 202, 32);

        bAddOperator.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        bAddOperator.setText("Add Operator");
        bAddOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddOperatorActionPerformed(evt);
            }
        });
        getContentPane().add(bAddOperator);
        bAddOperator.setBounds(10, 319, 165, 50);

        jButton2.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jButton2.setText("Delete Operator");
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 399, 165, 49);

        jButton3.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jButton3.setText("Search Operator");
        getContentPane().add(jButton3);
        jButton3.setBounds(340, 320, 187, 49);

        jButton4.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jButton4.setText("Show All Operator");
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 399, 187, 49);

        jButton5.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jButton5.setText("Show User Detail");
        getContentPane().add(jButton5);
        jButton5.setBounds(658, 319, 175, 50);

        jButton6.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jButton6.setText("Swich User");
        getContentPane().add(jButton6);
        jButton6.setBounds(658, 399, 175, 49);

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sukanta\\Pictures\\log out button.jpg")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(625, 20, 208, 69);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sukanta\\Pictures\\14_5.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 840, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int rply = JOptionPane.showConfirmDialog(this, "Are you sure to log out?");
	if(rply == JOptionPane.YES_OPTION)
	{
		JOptionPane.showMessageDialog(this, "You are successfully logged out.");
		JFrame AdminLoginGUI1 = new AdminLoginGUI1();
                AdminLoginGUI1.setVisible(true);
                setVisible(false);
	}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void bAddOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddOperatorActionPerformed
        JFrame RegistrationFrom = new RegistrationFrom();
	RegistrationFrom.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bAddOperatorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPageGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPageGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPageGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPageGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPageGUI1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddOperator;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lDate;
    private javax.swing.JLabel lDateValue;
    private javax.swing.JLabel lTime;
    private javax.swing.JLabel lTimeValue;
    // End of variables declaration//GEN-END:variables
}
