/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//package leave.application;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Sukanta
 */
public class AdminPage extends javax.swing.JFrame {
    private final String sysDate;
    private final String sysTime;

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        
        /********DATE**********************/
		
	Calendar cal = Calendar.getInstance();
		
	String cday = ""+cal.get(Calendar.DATE);
	int x =cal.get(Calendar.MONTH);
	String cmonth = ""+(x+1);
	String cyear =""+cal.get(Calendar.YEAR);
	sysDate = cday+" / "+cmonth+" / "+cyear;
		
	//lDateValue = new JLabel(sysDate);		
		
		
	String chr = ""+cal.get(Calendar.HOUR_OF_DAY);
	String cmin = ""+cal.get(Calendar.MINUTE);
	String csec =""+cal.get(Calendar.SECOND);
	sysTime = chr+" : "+cmin+ " : "+csec;
		
	/**************************************************/
        
        
        /************PRINT DATE ON LABEL********************/
        
        jLabelDateValue.setText(sysDate);
        jLabelTimeValue.setText(sysTime);
        
        /***************************************************/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAdminImage = new javax.swing.JLabel();
        jLabelWekcine = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jButtonCreateAnOperator = new javax.swing.JButton();
        jButtonSearchAnOperator = new javax.swing.JButton();
        jButtonDeleteAnOperator = new javax.swing.JButton();
        jButtonCreateAnEmployee = new javax.swing.JButton();
        jButtonSearchAnEmployee = new javax.swing.JButton();
        jButtonDeleteAnEmployee = new javax.swing.JButton();
        jButtonLoginHistory = new javax.swing.JButton();
        jLabelDate = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelDateValue = new javax.swing.JLabel();
        jLabelTimeValue = new javax.swing.JLabel();
        jButtonShowAllOperator = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Administrator");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setMaximizedBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setMaximumSize(new java.awt.Dimension(946, 496));
        setMinimumSize(new java.awt.Dimension(946, 496));
        setResizable(false);

        jLabelAdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.jpg"))); // NOI18N
        jLabelAdminImage.setText("jLabel1");

        jLabelWekcine.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabelWekcine.setForeground(new java.awt.Color(0, 51, 255));
        jLabelWekcine.setText("Welcome to Adminstrator");

        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log out button.jpg"))); // NOI18N
        jButtonLogout.setText("jButton1");
        jButtonLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jButtonCreateAnOperator.setBackground(new java.awt.Color(255, 0, 51));
        jButtonCreateAnOperator.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButtonCreateAnOperator.setForeground(new java.awt.Color(204, 204, 204));
        jButtonCreateAnOperator.setText("Create An Operator");
        jButtonCreateAnOperator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCreateAnOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateAnOperatorActionPerformed(evt);
            }
        });

        jButtonSearchAnOperator.setBackground(new java.awt.Color(255, 0, 51));
        jButtonSearchAnOperator.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButtonSearchAnOperator.setForeground(new java.awt.Color(204, 204, 204));
        jButtonSearchAnOperator.setText("Search An Operator");
        jButtonSearchAnOperator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonDeleteAnOperator.setBackground(new java.awt.Color(255, 0, 51));
        jButtonDeleteAnOperator.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButtonDeleteAnOperator.setForeground(new java.awt.Color(204, 204, 204));
        jButtonDeleteAnOperator.setText("Delete An Operator");
        jButtonDeleteAnOperator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonCreateAnEmployee.setBackground(new java.awt.Color(0, 153, 0));
        jButtonCreateAnEmployee.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButtonCreateAnEmployee.setForeground(new java.awt.Color(204, 204, 204));
        jButtonCreateAnEmployee.setText("Create An Employee");
        jButtonCreateAnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonSearchAnEmployee.setBackground(new java.awt.Color(0, 153, 0));
        jButtonSearchAnEmployee.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButtonSearchAnEmployee.setForeground(new java.awt.Color(204, 204, 204));
        jButtonSearchAnEmployee.setText("Search An Employee");
        jButtonSearchAnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonDeleteAnEmployee.setBackground(new java.awt.Color(0, 153, 0));
        jButtonDeleteAnEmployee.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButtonDeleteAnEmployee.setForeground(new java.awt.Color(204, 204, 204));
        jButtonDeleteAnEmployee.setText("Delete An Employee");
        jButtonDeleteAnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonLoginHistory.setBackground(new java.awt.Color(255, 51, 255));
        jButtonLoginHistory.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButtonLoginHistory.setForeground(new java.awt.Color(204, 204, 204));
        jButtonLoginHistory.setText("Login History");
        jButtonLoginHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelDate.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDate.setText("Current Date :");

        jLabelTime.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jLabelTime.setForeground(new java.awt.Color(255, 0, 51));
        jLabelTime.setText("Current Time :");

        jLabelDateValue.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N

        jLabelTimeValue.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N

        jButtonShowAllOperator.setBackground(new java.awt.Color(255, 0, 51));
        jButtonShowAllOperator.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        jButtonShowAllOperator.setForeground(new java.awt.Color(204, 204, 204));
        jButtonShowAllOperator.setText("Show All Operator");
        jButtonShowAllOperator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonShowAllOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllOperatorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(12, Short.MAX_VALUE)
                                .addComponent(jLabelWekcine, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonCreateAnOperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonSearchAnOperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonDeleteAnOperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(125, 125, 125)
                                        .addComponent(jButtonShowAllOperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelDateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelTimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(136, 136, 136)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonLoginHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCreateAnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSearchAnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteAnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWekcine, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLoginHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCreateAnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearchAnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteAnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCreateAnOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearchAnOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDeleteAnOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonShowAllOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Create an operator
     * 
     * @param evt 
     */
    
    
    private void jButtonCreateAnOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateAnOperatorActionPerformed
        // TODO add your handling code here:
        
        new OperatorRegistration().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonCreateAnOperatorActionPerformed

    
    /**
     * Logout
     * @param evt 
     */
    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        
        int rply = JOptionPane.showConfirmDialog(this, "Are you sure to logout?");
        
        if(rply == JOptionPane.YES_OPTION)  {
            
            JOptionPane.showMessageDialog(this, "Succesfully logged out");
            
            new LoginPage().setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonShowAllOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllOperatorActionPerformed
        // TODO add your handling code here:
        
        new OperatorDisplay().setVisible(true);
    }//GEN-LAST:event_jButtonShowAllOperatorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateAnEmployee;
    private javax.swing.JButton jButtonCreateAnOperator;
    private javax.swing.JButton jButtonDeleteAnEmployee;
    private javax.swing.JButton jButtonDeleteAnOperator;
    private javax.swing.JButton jButtonLoginHistory;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSearchAnEmployee;
    private javax.swing.JButton jButtonSearchAnOperator;
    private javax.swing.JButton jButtonShowAllOperator;
    private javax.swing.JLabel jLabelAdminImage;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDateValue;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTimeValue;
    private javax.swing.JLabel jLabelWekcine;
    // End of variables declaration//GEN-END:variables
}
