/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//package leave.application;

import javax.swing.JOptionPane;

/**
 *
 * @author Sukanta
 */
public class LoginPage extends javax.swing.JFrame {
    private String loginType;
    private String userID;
    private String password;

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcome = new javax.swing.JLabel();
        jLabelLoginType = new javax.swing.JLabel();
        jComboBoxLoginType = new javax.swing.JComboBox();
        jLabelUserID = new javax.swing.JLabel();
        jTextFieldUserID = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Service Biodata");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setMaximumSize(new java.awt.Dimension(946, 496));
        setMinimumSize(new java.awt.Dimension(946, 496));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelWelcome.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(51, 0, 255));
        jLabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcome.setText("Welcome to Serivice Biodata");
        getContentPane().add(jLabelWelcome);
        jLabelWelcome.setBounds(10, 10, 902, 78);

        jLabelLoginType.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabelLoginType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLoginType.setText("Login Type");
        getContentPane().add(jLabelLoginType);
        jLabelLoginType.setBounds(300, 180, 99, 33);

        jComboBoxLoginType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxLoginType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Operator", "Administrator" }));
        jComboBoxLoginType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jComboBoxLoginType);
        jComboBoxLoginType.setBounds(410, 180, 210, 30);

        jLabelUserID.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabelUserID.setText("User ID");
        getContentPane().add(jLabelUserID);
        jLabelUserID.setBounds(300, 220, 67, 33);

        jTextFieldUserID.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldUserID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldUserID);
        jTextFieldUserID.setBounds(410, 220, 210, 28);

        jLabelPassword.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabelPassword.setText("Password");
        getContentPane().add(jLabelPassword);
        jLabelPassword.setBounds(300, 260, 87, 33);

        jPasswordFieldPassword.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordFieldPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPasswordFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldPassword);
        jPasswordFieldPassword.setBounds(410, 260, 210, 28);

        jButtonLogin.setBackground(new java.awt.Color(0, 102, 0));
        jButtonLogin.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(204, 204, 204));
        jButtonLogin.setText("Login");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin);
        jButtonLogin.setBounds(300, 330, 140, 47);

        jButtonReset.setBackground(new java.awt.Color(255, 0, 0));
        jButtonReset.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(204, 204, 204));
        jButtonReset.setText("Reset");
        jButtonReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReset);
        jButtonReset.setBounds(480, 330, 140, 47);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/(8).jpg"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 950, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPasswordActionPerformed

    
    /**
     * Login
     * @param evt \
     */
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        
        /**
         * Check for login type
         */
        
        loginType = (String)jComboBoxLoginType.getSelectedItem();
        
        if(loginType.equals("Administrator"))   {
            
            if(jTextFieldUserID.getText().equals("admin") && jPasswordFieldPassword.getText().equals("264078"))    {
                
                JOptionPane.showMessageDialog(this, "Welcome to Administrator");
                new AdminPage().setVisible(true);
                setVisible(false);
            }
            
            else    {
                JOptionPane.showMessageDialog(this, "Incorrect UderID or Password.\nTry Again", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
        
        if(loginType.equals("Operator"))    {
            
            JOptionPane.showMessageDialog(this, "Page is under construction");
            
        }
        
        jTextFieldUserID.setText("");
        jPasswordFieldPassword.setText("");
    }//GEN-LAST:event_jButtonLoginActionPerformed

    
    /**
     * Reset
     * @param evt 
     */
    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        
        jTextFieldUserID.setText("");
        jPasswordFieldPassword.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox jComboBoxLoginType;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelLoginType;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUserID;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUserID;
    // End of variables declaration//GEN-END:variables
}
