/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package first;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sukanta
 */
public class HomePageGUI extends javax.swing.JFrame {

    /**
     * Creates new form HomePageGUI
     */
    public HomePageGUI() {
        initComponents();
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHomePageTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelLogInAs = new javax.swing.JLabel();
        buttonAdmin = new javax.swing.JButton();
        buttonUser = new javax.swing.JButton();
        labelHomePageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welocome to Bank of Kolkata");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(565, 300));
        setPreferredSize(new java.awt.Dimension(565, 340));
        getContentPane().setLayout(null);

        labelHomePageTitle.setFont(new java.awt.Font("Nyala", 1, 36)); // NOI18N
        labelHomePageTitle.setForeground(new java.awt.Color(61, 60, 171));
        labelHomePageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHomePageTitle.setText("WELCOME TO BANK OF KOLKATA");
        getContentPane().add(labelHomePageTitle);
        labelHomePageTitle.setBounds(10, 11, 545, 44);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 61, 545, 10);

        labelLogInAs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelLogInAs.setForeground(new java.awt.Color(166, 61, 169));
        labelLogInAs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogInAs.setText("Log in as");
        getContentPane().add(labelLogInAs);
        labelLogInAs.setBounds(10, 39, 545, 80);

        buttonAdmin.setBackground(new java.awt.Color(204, 204, 255));
        buttonAdmin.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        buttonAdmin.setForeground(new java.awt.Color(0, 0, 153));
        buttonAdmin.setText("Administrator");
        buttonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdminActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAdmin);
        buttonAdmin.setBounds(76, 188, 171, 52);

        buttonUser.setBackground(new java.awt.Color(251, 221, 221));
        buttonUser.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        buttonUser.setForeground(new java.awt.Color(255, 0, 51));
        buttonUser.setText("Operator");
        buttonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserActionPerformed(evt);
            }
        });
        getContentPane().add(buttonUser);
        buttonUser.setBounds(333, 188, 171, 52);

        labelHomePageBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sukanta\\Pictures\\5_2_2.jpg")); // NOI18N
        getContentPane().add(labelHomePageBackground);
        labelHomePageBackground.setBounds(0, 0, 570, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdminActionPerformed
        //JOptionPane.showMessageDialog(this, "Admin Button");
        JFrame AdminLoginGUI1 = new AdminLoginGUI1();
	AdminLoginGUI1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonAdminActionPerformed

    private void buttonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserActionPerformed
        JFrame OperatorLoginGUI = new OperatorLoginGUI();
	OperatorLoginGUI.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageGUI().setVisible(true);
                //new HomePageGUI().setResizable(false);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdmin;
    private javax.swing.JButton buttonUser;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelHomePageBackground;
    private javax.swing.JLabel labelHomePageTitle;
    private javax.swing.JLabel labelLogInAs;
    // End of variables declaration//GEN-END:variables
}
