/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package first;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Sukanta
 */
public class RegistrationFrom extends javax.swing.JFrame {
    private String sysDate,sysTime;

    /**
     * Creates new form RegistrationFrom
     */
    public RegistrationFrom() {
        initComponents();
        
        
        /****** System date and time**************/
        Calendar cal = Calendar.getInstance();
		
		String cday = ""+cal.get(Calendar.DATE);
		int x =cal.get(Calendar.MONTH);
		String cmonth = ""+(x+1);
		String cyear =""+cal.get(Calendar.YEAR);
		sysDate = cday+"/"+cmonth+"/"+cyear;
		
		//lDateValue=new JLabel(sysDate);	
                this.lDateValue.setText(sysDate);
		
		
		String chr = ""+cal.get(Calendar.HOUR_OF_DAY);
		String cmin = ""+cal.get(Calendar.MINUTE);
		String csec =""+cal.get(Calendar.SECOND);
		sysTime = chr+":"+cmin+":"+csec;
		
		//lTimeValue=new JLabel(sysTime);
                this.lTimeValue.setText(sysTime);
                /*********************************************/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGGender = new javax.swing.ButtonGroup();
        BGAccountType = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lFirstName = new javax.swing.JLabel();
        tFirstName = new javax.swing.JTextField();
        lLastName = new javax.swing.JLabel();
        tLastName = new javax.swing.JTextField();
        lAddress = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tAddress = new javax.swing.JTextArea();
        lMobileNumber = new javax.swing.JLabel();
        tMobileNumber = new javax.swing.JTextField();
        lLandLineNumber = new javax.swing.JLabel();
        tLandLineNumber = new javax.swing.JTextField();
        tNationality = new javax.swing.JTextField();
        lNationality = new javax.swing.JLabel();
        lProfessional = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        RBOther = new javax.swing.JRadioButton();
        RBSaving = new javax.swing.JRadioButton();
        lDOB = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RBMale = new javax.swing.JRadioButton();
        RBFemale = new javax.swing.JRadioButton();
        lGender = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        CBMonth = new javax.swing.JComboBox();
        CBYear = new javax.swing.JComboBox();
        CBDate = new javax.swing.JComboBox();
        lAccountType = new javax.swing.JLabel();
        CBAnualIncome = new javax.swing.JComboBox();
        lAnualIncome = new javax.swing.JLabel();
        lIdentityNumber = new javax.swing.JLabel();
        CBProfession = new javax.swing.JComboBox();
        lInitialDeposite = new javax.swing.JLabel();
        tInitialDeposite = new javax.swing.JTextField();
        lIndentityProof = new javax.swing.JLabel();
        CBIndentityProof = new javax.swing.JComboBox();
        lTime = new javax.swing.JLabel();
        tIdentityNumber = new javax.swing.JTextField();
        lAccountNumber = new javax.swing.JLabel();
        tOperatorID = new javax.swing.JTextField();
        lDate = new javax.swing.JLabel();
        lDateValue = new javax.swing.JLabel();
        lTimeValue = new javax.swing.JLabel();
        bSubmitOperator = new javax.swing.JButton();
        lOperatorID = new javax.swing.JLabel();
        lOperatorPassword = new javax.swing.JLabel();
        tAccountNumber = new javax.swing.JTextField();
        tOperatorPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 20, 0, 0));
        setMaximumSize(new java.awt.Dimension(868, 774));
        setMinimumSize(new java.awt.Dimension(868, 774));
        setResizable(false);

        lFirstName.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lFirstName.setForeground(new java.awt.Color(51, 51, 255));
        lFirstName.setText("First Name");

        lLastName.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lLastName.setForeground(new java.awt.Color(51, 51, 255));
        lLastName.setText("Last Name");

        lAddress.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lAddress.setForeground(new java.awt.Color(51, 51, 255));
        lAddress.setText("Address");

        tAddress.setColumns(20);
        tAddress.setRows(5);
        jScrollPane3.setViewportView(tAddress);

        lMobileNumber.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lMobileNumber.setForeground(new java.awt.Color(51, 51, 255));
        lMobileNumber.setText(" Mobile Number");

        lLandLineNumber.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lLandLineNumber.setForeground(new java.awt.Color(51, 51, 255));
        lLandLineNumber.setText("Land Line Number");

        lNationality.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lNationality.setForeground(new java.awt.Color(51, 51, 255));
        lNationality.setText("Nationality");

        lProfessional.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lProfessional.setForeground(new java.awt.Color(51, 51, 255));
        lProfessional.setText("Profession");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BGAccountType.add(RBOther);
        RBOther.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        RBOther.setText("Other");

        BGAccountType.add(RBSaving);
        RBSaving.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        RBSaving.setText("Savings");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(RBSaving)
                .addGap(18, 18, 18)
                .addComponent(RBOther)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBSaving)
                    .addComponent(RBOther))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        lDOB.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lDOB.setForeground(new java.awt.Color(51, 51, 255));
        lDOB.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lDOB.setText("DOB");

        BGGender.add(RBMale);
        RBMale.setText("Male");

        BGGender.add(RBFemale);
        RBFemale.setText("Female");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RBMale)
                .addGap(18, 18, 18)
                .addComponent(RBFemale)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBMale)
                    .addComponent(RBFemale))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lGender.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lGender.setForeground(new java.awt.Color(51, 51, 255));
        lGender.setText("Gender");

        CBMonth.setEditable(true);
        CBMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        CBYear.setEditable(true);
        CBYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));

        CBDate.setEditable(true);
        CBDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CBDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        lAccountType.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lAccountType.setForeground(new java.awt.Color(51, 51, 255));
        lAccountType.setText("Account Type");

        CBAnualIncome.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<50000", "50001-100000", "100001-600000", ">600000" }));

        lAnualIncome.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lAnualIncome.setForeground(new java.awt.Color(51, 51, 255));
        lAnualIncome.setText("Anual Income");

        lIdentityNumber.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lIdentityNumber.setForeground(new java.awt.Color(51, 51, 255));
        lIdentityNumber.setText("Coresponding Number of Identity Proof");

        CBProfession.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Govt. Service", "Private Sectore", "Buisness", "Other" }));

        lInitialDeposite.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lInitialDeposite.setForeground(new java.awt.Color(51, 51, 255));
        lInitialDeposite.setText("Initial Deposite");

        lIndentityProof.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lIndentityProof.setForeground(new java.awt.Color(51, 51, 255));
        lIndentityProof.setText("Identity Proof");

        CBIndentityProof.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PAN Card", "Voter Card", "Adhar Card", "Ration Card" }));

        lTime.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lTime.setForeground(new java.awt.Color(51, 51, 255));
        lTime.setText("Current Time");

        lAccountNumber.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lAccountNumber.setForeground(new java.awt.Color(51, 51, 255));
        lAccountNumber.setText("Account Number");

        lDate.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lDate.setForeground(new java.awt.Color(51, 51, 255));
        lDate.setText("Current Date");

        lDateValue.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lDateValue.setForeground(new java.awt.Color(255, 0, 0));

        lTimeValue.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lTimeValue.setForeground(new java.awt.Color(204, 0, 51));

        bSubmitOperator.setBackground(new java.awt.Color(0, 204, 102));
        bSubmitOperator.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bSubmitOperator.setForeground(new java.awt.Color(102, 102, 102));
        bSubmitOperator.setText("Submit");
        bSubmitOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitOperatorActionPerformed(evt);
            }
        });

        lOperatorID.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lOperatorID.setForeground(new java.awt.Color(51, 51, 255));
        lOperatorID.setText("Operator ID");

        lOperatorPassword.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        lOperatorPassword.setForeground(new java.awt.Color(51, 51, 255));
        lOperatorPassword.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tFirstName))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tLastName))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tNationality))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lLandLineNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tLandLineNumber))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tMobileNumber))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lGender, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lTime, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lTimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lDate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lDateValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(tAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 20, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lOperatorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tOperatorPassword)
                                        .addGap(2, 2, 2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                                .addComponent(bSubmitOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lAnualIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CBAnualIncome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lInitialDeposite, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tInitialDeposite, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lIdentityNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lIndentityProof, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CBIndentityProof, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lProfessional, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CBProfession, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(tIdentityNumber))))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lOperatorID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tOperatorID, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lGender, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(lAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLandLineNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lLandLineNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBProfession, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lProfessional, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBAnualIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lIndentityProof, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CBIndentityProof, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lAnualIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lInitialDeposite, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tInitialDeposite, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lIdentityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tIdentityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTime, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lTimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lOperatorID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tOperatorID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lOperatorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tOperatorPassword)))
                    .addComponent(bSubmitOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration From");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String firstName, lastName, gender, dob, address, mobileNumber,
                   landLineNumber, nationality, accountType, profession,
                   anualIncome, identityProof, identityNumber, accountNumber,
                   initialDeposite, operatorID, operatorPassword;
    
    OperatorRegistrationData refOperator;
    private void bSubmitOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitOperatorActionPerformed
        
        JOptionPane.showMessageDialog(this, "REGISTER BUTTON");
        
        firstName = tFirstName.getText().trim();
        lastName = tLastName.getText().trim();
        
        
        
        gender="";
        if(RBMale.isSelected())
        {
            gender="Male";
        }
        if(RBFemale.isSelected())
        {
            gender="Female";
        }
        
        
        
        String d=(String)CBDate.getSelectedItem();
	String m=(String)CBMonth.getSelectedItem();
	String y=(String)CBYear.getSelectedItem();
	dob=d + "-" + m + "-" + y;
        
        
        address = tAddress.getText().trim();
        mobileNumber = tMobileNumber.getText().trim();
        landLineNumber = tLandLineNumber.getText().trim();
        nationality = tNationality.getText().trim();
        
        
        accountType="";
        if(RBSaving.isSelected())
        {
            gender="Saving";
        }
        if(RBOther.isSelected())
        {
            gender="Other";
        }
        
        
        profession = (String)CBProfession.getSelectedItem();
        anualIncome = (String)CBAnualIncome.getSelectedItem();
        identityProof = (String)CBIndentityProof.getSelectedItem();
        initialDeposite = tInitialDeposite.getText().trim();
        identityNumber = tIdentityNumber.getText().trim();
        accountNumber = tAccountNumber.getText().trim();
        operatorID = tOperatorID.getText().trim();
        operatorPassword = tOperatorPassword.getText().trim();
        
        
        
        refOperator = new OperatorRegistrationData();
        
        refOperator.setFirstName(firstName);
        refOperator.setLastName(lastName);
        refOperator.setGender(gender);
        refOperator.setDob(dob);
        refOperator.setAddress(address);
        refOperator.setMobileNumber(mobileNumber);
        refOperator.setLandLineNumber(landLineNumber);
        refOperator.setNationality(nationality);
        refOperator.setAccountType(accountType);
        refOperator.setProfession(profession);
        refOperator.setAnualIncome(anualIncome);
        refOperator.setIdentityProff(identityProof);
        refOperator.setIdentityNumber(identityNumber);
        refOperator.setIntialDeposite(initialDeposite);
        refOperator.setAccountNumber(accountNumber);
        refOperator.setOperatorID(operatorID);
        refOperator.setOperatorPassword(operatorPassword);
        refOperator.setDate(sysDate);
        refOperator.setTime(sysTime);
        
        int rply = JOptionPane.showConfirmDialog(this, "Are you sure to register?");
        if(rply == JOptionPane.YES_OPTION)
        {
             new AddInformationOperator(refOperator);
             JOptionPane.showMessageDialog(this, "Successfully registerd");
        }
        
        
    }//GEN-LAST:event_bSubmitOperatorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFrom().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGAccountType;
    private javax.swing.ButtonGroup BGGender;
    private javax.swing.JComboBox CBAnualIncome;
    private javax.swing.JComboBox CBDate;
    private javax.swing.JComboBox CBIndentityProof;
    private javax.swing.JComboBox CBMonth;
    private javax.swing.JComboBox CBProfession;
    private javax.swing.JComboBox CBYear;
    private javax.swing.JRadioButton RBFemale;
    private javax.swing.JRadioButton RBMale;
    private javax.swing.JRadioButton RBOther;
    private javax.swing.JRadioButton RBSaving;
    private javax.swing.JButton bSubmitOperator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lAccountNumber;
    private javax.swing.JLabel lAccountType;
    private javax.swing.JLabel lAddress;
    private javax.swing.JLabel lAnualIncome;
    private javax.swing.JLabel lDOB;
    private javax.swing.JLabel lDate;
    private javax.swing.JLabel lDateValue;
    private javax.swing.JLabel lFirstName;
    private javax.swing.JLabel lGender;
    private javax.swing.JLabel lIdentityNumber;
    private javax.swing.JLabel lIndentityProof;
    private javax.swing.JLabel lInitialDeposite;
    private javax.swing.JLabel lLandLineNumber;
    private javax.swing.JLabel lLastName;
    private javax.swing.JLabel lMobileNumber;
    private javax.swing.JLabel lNationality;
    private javax.swing.JLabel lOperatorID;
    private javax.swing.JLabel lOperatorPassword;
    private javax.swing.JLabel lProfessional;
    private javax.swing.JLabel lTime;
    private javax.swing.JLabel lTimeValue;
    private javax.swing.JTextField tAccountNumber;
    private javax.swing.JTextArea tAddress;
    private javax.swing.JTextField tFirstName;
    private javax.swing.JTextField tIdentityNumber;
    private javax.swing.JTextField tInitialDeposite;
    private javax.swing.JTextField tLandLineNumber;
    private javax.swing.JTextField tLastName;
    private javax.swing.JTextField tMobileNumber;
    private javax.swing.JTextField tNationality;
    private javax.swing.JTextField tOperatorID;
    private javax.swing.JPasswordField tOperatorPassword;
    // End of variables declaration//GEN-END:variables
}
